// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/primeage/notification/notification.proto

package notification

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendSMSRequest never carries message text.
//
// The caller names a template and supplies its data, which keeps DLT-registered
// wording in one place and stops a caller inventing text no template covers. An
// OTP therefore travels inside data_map rather than as a named field, so this
// service has no reason to treat it as special — or to log it.
type SendSMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	TemplateName  string                 `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	DataMap       map[string]string      `protobuf:"bytes,3,rep,name=data_map,json=dataMap,proto3" json:"data_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Priority      string                 `protobuf:"bytes,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSRequest) Reset() {
	*x = SendSMSRequest{}
	mi := &file_proto_primeage_notification_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSRequest) ProtoMessage() {}

func (x *SendSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_notification_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSRequest.ProtoReflect.Descriptor instead.
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_notification_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendSMSRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendSMSRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SendSMSRequest) GetDataMap() map[string]string {
	if x != nil {
		return x.DataMap
	}
	return nil
}

func (x *SendSMSRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *SendSMSRequest) GetPriority() string {
	if x != nil {
		return x.Priority
	}
	return ""
}

// SendSMSResponse reports delivery.
//
// status is a string rather than a bool because "unsupported_destination" has to
// be distinguishable from a generic failure — the caller renders a different
// message to the user for each. It is a field rather than a gRPC status code for
// that reason: it is an outcome, not a transport fault.
type SendSMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CorrelationId string                 `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSResponse) Reset() {
	*x = SendSMSResponse{}
	mi := &file_proto_primeage_notification_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSResponse) ProtoMessage() {}

func (x *SendSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_notification_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSResponse.ProtoReflect.Descriptor instead.
func (*SendSMSResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_notification_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendSMSResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendSMSResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *SendSMSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_primeage_notification_notification_proto protoreflect.FileDescriptor

const file_proto_primeage_notification_notification_proto_rawDesc = "" +
	"\n" +
	".proto/primeage/notification/notification.proto\x12\x15primeage.notification\"\x84\x02\n" +
	"\x0eSendSMSRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12#\n" +
	"\rtemplate_name\x18\x02 \x01(\tR\ftemplateName\x12M\n" +
	"\bdata_map\x18\x03 \x03(\v22.primeage.notification.SendSMSRequest.DataMapEntryR\adataMap\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\tR\bpriority\x1a:\n" +
	"\fDataMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\x0fSendSMSResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0ecorrelation_id\x18\x02 \x01(\tR\rcorrelationId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2q\n" +
	"\x13NotificationService\x12Z\n" +
	"\aSendSMS\x12%.primeage.notification.SendSMSRequest\x1a&.primeage.notification.SendSMSResponse\"\x00B@Z>github.com/primeage-health/primeageutils/genproto/notificationb\x06proto3"

var (
	file_proto_primeage_notification_notification_proto_rawDescOnce sync.Once
	file_proto_primeage_notification_notification_proto_rawDescData []byte
)

func file_proto_primeage_notification_notification_proto_rawDescGZIP() []byte {
	file_proto_primeage_notification_notification_proto_rawDescOnce.Do(func() {
		file_proto_primeage_notification_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_primeage_notification_notification_proto_rawDesc), len(file_proto_primeage_notification_notification_proto_rawDesc)))
	})
	return file_proto_primeage_notification_notification_proto_rawDescData
}

var file_proto_primeage_notification_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_primeage_notification_notification_proto_goTypes = []any{
	(*SendSMSRequest)(nil),  // 0: primeage.notification.SendSMSRequest
	(*SendSMSResponse)(nil), // 1: primeage.notification.SendSMSResponse
	nil,                     // 2: primeage.notification.SendSMSRequest.DataMapEntry
}
var file_proto_primeage_notification_notification_proto_depIdxs = []int32{
	2, // 0: primeage.notification.SendSMSRequest.data_map:type_name -> primeage.notification.SendSMSRequest.DataMapEntry
	0, // 1: primeage.notification.NotificationService.SendSMS:input_type -> primeage.notification.SendSMSRequest
	1, // 2: primeage.notification.NotificationService.SendSMS:output_type -> primeage.notification.SendSMSResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_primeage_notification_notification_proto_init() }
func file_proto_primeage_notification_notification_proto_init() {
	if File_proto_primeage_notification_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_primeage_notification_notification_proto_rawDesc), len(file_proto_primeage_notification_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_primeage_notification_notification_proto_goTypes,
		DependencyIndexes: file_proto_primeage_notification_notification_proto_depIdxs,
		MessageInfos:      file_proto_primeage_notification_notification_proto_msgTypes,
	}.Build()
	File_proto_primeage_notification_notification_proto = out.File
	file_proto_primeage_notification_notification_proto_goTypes = nil
	file_proto_primeage_notification_notification_proto_depIdxs = nil
}
