// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/primeage/identity/identity.proto

package identity

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_ResolveIdentifier_FullMethodName      = "/primeage.identity.IdentityService/ResolveIdentifier"
	IdentityService_TenantState_FullMethodName            = "/primeage.identity.IdentityService/TenantState"
	IdentityService_ClaimIdentity_FullMethodName          = "/primeage.identity.IdentityService/ClaimIdentity"
	IdentityService_ReleaseIdentity_FullMethodName        = "/primeage.identity.IdentityService/ReleaseIdentity"
	IdentityService_MarkIdentifierVerified_FullMethodName = "/primeage.identity.IdentityService/MarkIdentifierVerified"
	IdentityService_ListTenantDomains_FullMethodName      = "/primeage.identity.IdentityService/ListTenantDomains"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService is what auth.primeage.life may ask of backend.primeage.life,
// and the whole of the identity layer's external surface.
//
// It is deliberately narrow. Backend owns which person holds an identifier and
// which tenants exist; auth owns credentials, sessions and each tenant's
// accounts. So auth can resolve, claim, release and verify — and nothing here
// lets it read a person wholesale, list who is registered, or change a tenant's
// status.
//
// Every sign-in makes one call across this boundary before it can know which
// tenant it is signing in to. That is a real cost of the split: sign-in cannot
// proceed while backend is unreachable. The calls are short-timeout for that
// reason, and their failures map to the same uniform login rejection as any
// other, never to a message naming which service is down.
type IdentityServiceClient interface {
	// ResolveIdentifier maps an identifier to the person holding it and the single
	// tenant they sign in to. A person with zero or several memberships is
	// NOT_FOUND, since sign-in has no tenant to resolve to in either case.
	ResolveIdentifier(ctx context.Context, in *ResolveIdentifierRequest, opts ...grpc.CallOption) (*Identity, error)
	// TenantState reports whether a tenant's accounts may still authenticate.
	// NOT_FOUND when the domain is not a registered tenant.
	TenantState(ctx context.Context, in *TenantStateRequest, opts ...grpc.CallOption) (*TenantStateResponse, error)
	// ClaimIdentity binds an account's identifiers to a person, creating one when
	// the phone number is claimed by nobody.
	ClaimIdentity(ctx context.Context, in *ClaimIdentityRequest, opts ...grpc.CallOption) (*ClaimIdentityResponse, error)
	// ReleaseIdentity removes a person the caller created and could not use.
	//
	// The caller asserts that; this service cannot verify it, because only the
	// caller knows whether its own account write failed. That is why the method is
	// service-authenticated and why ClaimIdentity reports whether it created the
	// person at all. Already gone is success, not NOT_FOUND — it is the outcome
	// the call wanted.
	ReleaseIdentity(ctx context.Context, in *ReleaseIdentityRequest, opts ...grpc.CallOption) (*ReleaseIdentityResponse, error)
	// MarkIdentifierVerified records proof of control of an identifier. An
	// operator typing a number at onboarding was an assertion; an OTP is what
	// makes it a verification.
	MarkIdentifierVerified(ctx context.Context, in *MarkIdentifierVerifiedRequest, opts ...grpc.CallOption) (*MarkIdentifierVerifiedResponse, error)
	// ListTenantDomains returns every tenant whose storage exists, which is what
	// the auth service's boot-time index sweep iterates. Tenants still being
	// provisioned are absent: their onboarding never finished, so a caller
	// sweeping indexes across them would be preparing storage for a tenant that
	// may never exist.
	ListTenantDomains(ctx context.Context, in *ListTenantDomainsRequest, opts ...grpc.CallOption) (*ListTenantDomainsResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) ResolveIdentifier(ctx context.Context, in *ResolveIdentifierRequest, opts ...grpc.CallOption) (*Identity, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Identity)
	err := c.cc.Invoke(ctx, IdentityService_ResolveIdentifier_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) TenantState(ctx context.Context, in *TenantStateRequest, opts ...grpc.CallOption) (*TenantStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TenantStateResponse)
	err := c.cc.Invoke(ctx, IdentityService_TenantState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ClaimIdentity(ctx context.Context, in *ClaimIdentityRequest, opts ...grpc.CallOption) (*ClaimIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_ClaimIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ReleaseIdentity(ctx context.Context, in *ReleaseIdentityRequest, opts ...grpc.CallOption) (*ReleaseIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseIdentityResponse)
	err := c.cc.Invoke(ctx, IdentityService_ReleaseIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) MarkIdentifierVerified(ctx context.Context, in *MarkIdentifierVerifiedRequest, opts ...grpc.CallOption) (*MarkIdentifierVerifiedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkIdentifierVerifiedResponse)
	err := c.cc.Invoke(ctx, IdentityService_MarkIdentifierVerified_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ListTenantDomains(ctx context.Context, in *ListTenantDomainsRequest, opts ...grpc.CallOption) (*ListTenantDomainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantDomainsResponse)
	err := c.cc.Invoke(ctx, IdentityService_ListTenantDomains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService is what auth.primeage.life may ask of backend.primeage.life,
// and the whole of the identity layer's external surface.
//
// It is deliberately narrow. Backend owns which person holds an identifier and
// which tenants exist; auth owns credentials, sessions and each tenant's
// accounts. So auth can resolve, claim, release and verify — and nothing here
// lets it read a person wholesale, list who is registered, or change a tenant's
// status.
//
// Every sign-in makes one call across this boundary before it can know which
// tenant it is signing in to. That is a real cost of the split: sign-in cannot
// proceed while backend is unreachable. The calls are short-timeout for that
// reason, and their failures map to the same uniform login rejection as any
// other, never to a message naming which service is down.
type IdentityServiceServer interface {
	// ResolveIdentifier maps an identifier to the person holding it and the single
	// tenant they sign in to. A person with zero or several memberships is
	// NOT_FOUND, since sign-in has no tenant to resolve to in either case.
	ResolveIdentifier(context.Context, *ResolveIdentifierRequest) (*Identity, error)
	// TenantState reports whether a tenant's accounts may still authenticate.
	// NOT_FOUND when the domain is not a registered tenant.
	TenantState(context.Context, *TenantStateRequest) (*TenantStateResponse, error)
	// ClaimIdentity binds an account's identifiers to a person, creating one when
	// the phone number is claimed by nobody.
	ClaimIdentity(context.Context, *ClaimIdentityRequest) (*ClaimIdentityResponse, error)
	// ReleaseIdentity removes a person the caller created and could not use.
	//
	// The caller asserts that; this service cannot verify it, because only the
	// caller knows whether its own account write failed. That is why the method is
	// service-authenticated and why ClaimIdentity reports whether it created the
	// person at all. Already gone is success, not NOT_FOUND — it is the outcome
	// the call wanted.
	ReleaseIdentity(context.Context, *ReleaseIdentityRequest) (*ReleaseIdentityResponse, error)
	// MarkIdentifierVerified records proof of control of an identifier. An
	// operator typing a number at onboarding was an assertion; an OTP is what
	// makes it a verification.
	MarkIdentifierVerified(context.Context, *MarkIdentifierVerifiedRequest) (*MarkIdentifierVerifiedResponse, error)
	// ListTenantDomains returns every tenant whose storage exists, which is what
	// the auth service's boot-time index sweep iterates. Tenants still being
	// provisioned are absent: their onboarding never finished, so a caller
	// sweeping indexes across them would be preparing storage for a tenant that
	// may never exist.
	ListTenantDomains(context.Context, *ListTenantDomainsRequest) (*ListTenantDomainsResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) ResolveIdentifier(context.Context, *ResolveIdentifierRequest) (*Identity, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIdentifier not implemented")
}
func (UnimplementedIdentityServiceServer) TenantState(context.Context, *TenantStateRequest) (*TenantStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TenantState not implemented")
}
func (UnimplementedIdentityServiceServer) ClaimIdentity(context.Context, *ClaimIdentityRequest) (*ClaimIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) ReleaseIdentity(context.Context, *ReleaseIdentityRequest) (*ReleaseIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseIdentity not implemented")
}
func (UnimplementedIdentityServiceServer) MarkIdentifierVerified(context.Context, *MarkIdentifierVerifiedRequest) (*MarkIdentifierVerifiedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkIdentifierVerified not implemented")
}
func (UnimplementedIdentityServiceServer) ListTenantDomains(context.Context, *ListTenantDomainsRequest) (*ListTenantDomainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenantDomains not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_ResolveIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ResolveIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ResolveIdentifier_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ResolveIdentifier(ctx, req.(*ResolveIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_TenantState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).TenantState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_TenantState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).TenantState(ctx, req.(*TenantStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ClaimIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ClaimIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ClaimIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ClaimIdentity(ctx, req.(*ClaimIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ReleaseIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ReleaseIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ReleaseIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ReleaseIdentity(ctx, req.(*ReleaseIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_MarkIdentifierVerified_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkIdentifierVerifiedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).MarkIdentifierVerified(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_MarkIdentifierVerified_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).MarkIdentifierVerified(ctx, req.(*MarkIdentifierVerifiedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ListTenantDomains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantDomainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ListTenantDomains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ListTenantDomains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ListTenantDomains(ctx, req.(*ListTenantDomainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primeage.identity.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveIdentifier",
			Handler:    _IdentityService_ResolveIdentifier_Handler,
		},
		{
			MethodName: "TenantState",
			Handler:    _IdentityService_TenantState_Handler,
		},
		{
			MethodName: "ClaimIdentity",
			Handler:    _IdentityService_ClaimIdentity_Handler,
		},
		{
			MethodName: "ReleaseIdentity",
			Handler:    _IdentityService_ReleaseIdentity_Handler,
		},
		{
			MethodName: "MarkIdentifierVerified",
			Handler:    _IdentityService_MarkIdentifierVerified_Handler,
		},
		{
			MethodName: "ListTenantDomains",
			Handler:    _IdentityService_ListTenantDomains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/primeage/identity/identity.proto",
}
