// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/primeage/identity/identity.proto

package identity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveIdentifierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIdentifierRequest) Reset() {
	*x = ResolveIdentifierRequest{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIdentifierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIdentifierRequest) ProtoMessage() {}

func (x *ResolveIdentifierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIdentifierRequest.ProtoReflect.Descriptor instead.
func (*ResolveIdentifierRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveIdentifierRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ResolveIdentifierRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Eid           string                 `protobuf:"bytes,3,opt,name=eid,proto3" json:"eid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *Identity) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Identity) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

// Applicant is someone part-way through agency onboarding.
//
// It carries no domain, and that is the whole difference from Identity: an
// applicant holds no membership, so there is no tenant to resolve to and a token
// minted from this must not be able to name one.
type Applicant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	EmailId       string                 `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Applicant) Reset() {
	*x = Applicant{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Applicant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Applicant) ProtoMessage() {}

func (x *Applicant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Applicant.ProtoReflect.Descriptor instead.
func (*Applicant) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{2}
}

func (x *Applicant) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *Applicant) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *Applicant) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *Applicant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TenantStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantStateRequest) Reset() {
	*x = TenantStateRequest{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantStateRequest) ProtoMessage() {}

func (x *TenantStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantStateRequest.ProtoReflect.Descriptor instead.
func (*TenantStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{3}
}

func (x *TenantStateRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type TenantStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantStateResponse) Reset() {
	*x = TenantStateResponse{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantStateResponse) ProtoMessage() {}

func (x *TenantStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantStateResponse.ProtoReflect.Descriptor instead.
func (*TenantStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{4}
}

func (x *TenantStateResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *TenantStateResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TenantStateResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

// ClaimIdentityRequest binds an account's identifiers to a person.
//
// eid is the account id the caller proposes. It is used only when this call
// creates the person; an existing person keeps the id it already carries, and
// the response is what the caller must adopt.
type ClaimIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailId       string                 `protobuf:"bytes,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Eid           string                 `protobuf:"bytes,4,opt,name=eid,proto3" json:"eid,omitempty"`
	ActorId       string                 `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,6,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimIdentityRequest) Reset() {
	*x = ClaimIdentityRequest{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimIdentityRequest) ProtoMessage() {}

func (x *ClaimIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimIdentityRequest.ProtoReflect.Descriptor instead.
func (*ClaimIdentityRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimIdentityRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ClaimIdentityRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *ClaimIdentityRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ClaimIdentityRequest) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

func (x *ClaimIdentityRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *ClaimIdentityRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// ClaimIdentityResponse is a settled claim.
//
// created reports whether this call brought the person into existence, which is
// the only case in which the caller may release it after a failure.
//
// conflict is a machine-readable refusal reason carried in the response rather
// than raised as ALREADY_EXISTS, because the caller has to distinguish which
// identifier collided in order to name the field to the user, and a status code
// cannot say that without the caller parsing prose.
//
// It stays a string rather than an enum so an unrecognised code passes through
// intact. The caller switches on the two it knows and treats anything else as no
// conflict, which is the safe reading; an enum would flatten a code added
// server-side into UNSPECIFIED until every client regenerated.
//
// The two codes in use:
//
//	identifier_claimed_by_other_tenant — the identifier belongs to a person
//	  holding no membership in the requested tenant. That person may hold a live
//	  account elsewhere, so nothing here is safe to overwrite.
//	email_claimed_by_other_person — the email address specifically collided.
type ClaimIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Eid           string                 `protobuf:"bytes,2,opt,name=eid,proto3" json:"eid,omitempty"`
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Conflict      string                 `protobuf:"bytes,4,opt,name=conflict,proto3" json:"conflict,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimIdentityResponse) Reset() {
	*x = ClaimIdentityResponse{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimIdentityResponse) ProtoMessage() {}

func (x *ClaimIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimIdentityResponse.ProtoReflect.Descriptor instead.
func (*ClaimIdentityResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimIdentityResponse) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *ClaimIdentityResponse) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

func (x *ClaimIdentityResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *ClaimIdentityResponse) GetConflict() string {
	if x != nil {
		return x.Conflict
	}
	return ""
}

func (x *ClaimIdentityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReleaseIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonId      string                 `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIdentityRequest) Reset() {
	*x = ReleaseIdentityRequest{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIdentityRequest) ProtoMessage() {}

func (x *ReleaseIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIdentityRequest.ProtoReflect.Descriptor instead.
func (*ReleaseIdentityRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseIdentityRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

type ReleaseIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseIdentityResponse) Reset() {
	*x = ReleaseIdentityResponse{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseIdentityResponse) ProtoMessage() {}

func (x *ReleaseIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseIdentityResponse.ProtoReflect.Descriptor instead.
func (*ReleaseIdentityResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{8}
}

type MarkIdentifierVerifiedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	VerifiedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkIdentifierVerifiedRequest) Reset() {
	*x = MarkIdentifierVerifiedRequest{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkIdentifierVerifiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkIdentifierVerifiedRequest) ProtoMessage() {}

func (x *MarkIdentifierVerifiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkIdentifierVerifiedRequest.ProtoReflect.Descriptor instead.
func (*MarkIdentifierVerifiedRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{9}
}

func (x *MarkIdentifierVerifiedRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MarkIdentifierVerifiedRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *MarkIdentifierVerifiedRequest) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

type MarkIdentifierVerifiedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkIdentifierVerifiedResponse) Reset() {
	*x = MarkIdentifierVerifiedResponse{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkIdentifierVerifiedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkIdentifierVerifiedResponse) ProtoMessage() {}

func (x *MarkIdentifierVerifiedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkIdentifierVerifiedResponse.ProtoReflect.Descriptor instead.
func (*MarkIdentifierVerifiedResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{10}
}

type ListTenantDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantDomainsRequest) Reset() {
	*x = ListTenantDomainsRequest{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantDomainsRequest) ProtoMessage() {}

func (x *ListTenantDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantDomainsRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{11}
}

type ListTenantDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantDomainsResponse) Reset() {
	*x = ListTenantDomainsResponse{}
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantDomainsResponse) ProtoMessage() {}

func (x *ListTenantDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_identity_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantDomainsResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_identity_identity_proto_rawDescGZIP(), []int{12}
}

func (x *ListTenantDomainsResponse) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

var File_proto_primeage_identity_identity_proto protoreflect.FileDescriptor

const file_proto_primeage_identity_identity_proto_rawDesc = "" +
	"\n" +
	"&proto/primeage/identity/identity.proto\x12\x11primeage.identity\x1a\x1fgoogle/protobuf/timestamp.proto\"D\n" +
	"\x18ResolveIdentifierRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"Q\n" +
	"\bIdentity\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x10\n" +
	"\x03eid\x18\x03 \x01(\tR\x03eid\"\x82\x01\n" +
	"\tApplicant\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12%\n" +
	"\x0eapplication_id\x18\x02 \x01(\tR\rapplicationId\x12\x19\n" +
	"\bemail_id\x18\x03 \x01(\tR\aemailId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\",\n" +
	"\x12TenantStateRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"]\n" +
	"\x13TenantStateResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\"\xb6\x01\n" +
	"\x14ClaimIdentityRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\bemail_id\x18\x02 \x01(\tR\aemailId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x10\n" +
	"\x03eid\x18\x04 \x01(\tR\x03eid\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x1b\n" +
	"\tdevice_id\x18\x06 \x01(\tR\bdeviceId\"\x96\x01\n" +
	"\x15ClaimIdentityResponse\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\x12\x10\n" +
	"\x03eid\x18\x02 \x01(\tR\x03eid\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x1a\n" +
	"\bconflict\x18\x04 \x01(\tR\bconflict\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"5\n" +
	"\x16ReleaseIdentityRequest\x12\x1b\n" +
	"\tperson_id\x18\x01 \x01(\tR\bpersonId\"\x19\n" +
	"\x17ReleaseIdentityResponse\"\x86\x01\n" +
	"\x1dMarkIdentifierVerifiedRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12;\n" +
	"\vverified_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\" \n" +
	"\x1eMarkIdentifierVerifiedResponse\"\x1a\n" +
	"\x18ListTenantDomainsRequest\"5\n" +
	"\x19ListTenantDomainsResponse\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomains2\xf8\x05\n" +
	"\x0fIdentityService\x12_\n" +
	"\x11ResolveIdentifier\x12+.primeage.identity.ResolveIdentifierRequest\x1a\x1b.primeage.identity.Identity\"\x00\x12_\n" +
	"\x10ResolveApplicant\x12+.primeage.identity.ResolveIdentifierRequest\x1a\x1c.primeage.identity.Applicant\"\x00\x12^\n" +
	"\vTenantState\x12%.primeage.identity.TenantStateRequest\x1a&.primeage.identity.TenantStateResponse\"\x00\x12d\n" +
	"\rClaimIdentity\x12'.primeage.identity.ClaimIdentityRequest\x1a(.primeage.identity.ClaimIdentityResponse\"\x00\x12j\n" +
	"\x0fReleaseIdentity\x12).primeage.identity.ReleaseIdentityRequest\x1a*.primeage.identity.ReleaseIdentityResponse\"\x00\x12\x7f\n" +
	"\x16MarkIdentifierVerified\x120.primeage.identity.MarkIdentifierVerifiedRequest\x1a1.primeage.identity.MarkIdentifierVerifiedResponse\"\x00\x12p\n" +
	"\x11ListTenantDomains\x12+.primeage.identity.ListTenantDomainsRequest\x1a,.primeage.identity.ListTenantDomainsResponse\"\x00B<Z:github.com/primeage-health/primeageutils/genproto/identityb\x06proto3"

var (
	file_proto_primeage_identity_identity_proto_rawDescOnce sync.Once
	file_proto_primeage_identity_identity_proto_rawDescData []byte
)

func file_proto_primeage_identity_identity_proto_rawDescGZIP() []byte {
	file_proto_primeage_identity_identity_proto_rawDescOnce.Do(func() {
		file_proto_primeage_identity_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_primeage_identity_identity_proto_rawDesc), len(file_proto_primeage_identity_identity_proto_rawDesc)))
	})
	return file_proto_primeage_identity_identity_proto_rawDescData
}

var file_proto_primeage_identity_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_primeage_identity_identity_proto_goTypes = []any{
	(*ResolveIdentifierRequest)(nil),       // 0: primeage.identity.ResolveIdentifierRequest
	(*Identity)(nil),                       // 1: primeage.identity.Identity
	(*Applicant)(nil),                      // 2: primeage.identity.Applicant
	(*TenantStateRequest)(nil),             // 3: primeage.identity.TenantStateRequest
	(*TenantStateResponse)(nil),            // 4: primeage.identity.TenantStateResponse
	(*ClaimIdentityRequest)(nil),           // 5: primeage.identity.ClaimIdentityRequest
	(*ClaimIdentityResponse)(nil),          // 6: primeage.identity.ClaimIdentityResponse
	(*ReleaseIdentityRequest)(nil),         // 7: primeage.identity.ReleaseIdentityRequest
	(*ReleaseIdentityResponse)(nil),        // 8: primeage.identity.ReleaseIdentityResponse
	(*MarkIdentifierVerifiedRequest)(nil),  // 9: primeage.identity.MarkIdentifierVerifiedRequest
	(*MarkIdentifierVerifiedResponse)(nil), // 10: primeage.identity.MarkIdentifierVerifiedResponse
	(*ListTenantDomainsRequest)(nil),       // 11: primeage.identity.ListTenantDomainsRequest
	(*ListTenantDomainsResponse)(nil),      // 12: primeage.identity.ListTenantDomainsResponse
	(*timestamppb.Timestamp)(nil),          // 13: google.protobuf.Timestamp
}
var file_proto_primeage_identity_identity_proto_depIdxs = []int32{
	13, // 0: primeage.identity.MarkIdentifierVerifiedRequest.verified_at:type_name -> google.protobuf.Timestamp
	0,  // 1: primeage.identity.IdentityService.ResolveIdentifier:input_type -> primeage.identity.ResolveIdentifierRequest
	0,  // 2: primeage.identity.IdentityService.ResolveApplicant:input_type -> primeage.identity.ResolveIdentifierRequest
	3,  // 3: primeage.identity.IdentityService.TenantState:input_type -> primeage.identity.TenantStateRequest
	5,  // 4: primeage.identity.IdentityService.ClaimIdentity:input_type -> primeage.identity.ClaimIdentityRequest
	7,  // 5: primeage.identity.IdentityService.ReleaseIdentity:input_type -> primeage.identity.ReleaseIdentityRequest
	9,  // 6: primeage.identity.IdentityService.MarkIdentifierVerified:input_type -> primeage.identity.MarkIdentifierVerifiedRequest
	11, // 7: primeage.identity.IdentityService.ListTenantDomains:input_type -> primeage.identity.ListTenantDomainsRequest
	1,  // 8: primeage.identity.IdentityService.ResolveIdentifier:output_type -> primeage.identity.Identity
	2,  // 9: primeage.identity.IdentityService.ResolveApplicant:output_type -> primeage.identity.Applicant
	4,  // 10: primeage.identity.IdentityService.TenantState:output_type -> primeage.identity.TenantStateResponse
	6,  // 11: primeage.identity.IdentityService.ClaimIdentity:output_type -> primeage.identity.ClaimIdentityResponse
	8,  // 12: primeage.identity.IdentityService.ReleaseIdentity:output_type -> primeage.identity.ReleaseIdentityResponse
	10, // 13: primeage.identity.IdentityService.MarkIdentifierVerified:output_type -> primeage.identity.MarkIdentifierVerifiedResponse
	12, // 14: primeage.identity.IdentityService.ListTenantDomains:output_type -> primeage.identity.ListTenantDomainsResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_primeage_identity_identity_proto_init() }
func file_proto_primeage_identity_identity_proto_init() {
	if File_proto_primeage_identity_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_primeage_identity_identity_proto_rawDesc), len(file_proto_primeage_identity_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_primeage_identity_identity_proto_goTypes,
		DependencyIndexes: file_proto_primeage_identity_identity_proto_depIdxs,
		MessageInfos:      file_proto_primeage_identity_identity_proto_msgTypes,
	}.Build()
	File_proto_primeage_identity_identity_proto = out.File
	file_proto_primeage_identity_identity_proto_goTypes = nil
	file_proto_primeage_identity_identity_proto_depIdxs = nil
}
