// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/primeage/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account is one account inside a tenant. Only what the admin console drills
// into — nothing about credentials or sessions crosses this boundary.
type Account struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UniqueId    string                 `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	PhoneNumber string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailId     string                 `protobuf:"bytes,3,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Name        string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Role        string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	Domain      string                 `protobuf:"bytes,6,opt,name=domain,proto3" json:"domain,omitempty"`
	Status      string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt   string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Not populated today. The field exists because the caller's view of an
	// account already carries it, and leaving a gap in the numbering would be
	// worse than an empty string.
	LastLoginAt   string `protobuf:"bytes,9,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *Account) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Account) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Account) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Account) GetLastLoginAt() string {
	if x != nil {
		return x.LastLoginAt
	}
	return ""
}

type PrepareTenantStorageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareTenantStorageRequest) Reset() {
	*x = PrepareTenantStorageRequest{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTenantStorageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTenantStorageRequest) ProtoMessage() {}

func (x *PrepareTenantStorageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTenantStorageRequest.ProtoReflect.Descriptor instead.
func (*PrepareTenantStorageRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareTenantStorageRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type PrepareTenantStorageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareTenantStorageResponse) Reset() {
	*x = PrepareTenantStorageResponse{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareTenantStorageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareTenantStorageResponse) ProtoMessage() {}

func (x *PrepareTenantStorageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareTenantStorageResponse.ProtoReflect.Descriptor instead.
func (*PrepareTenantStorageResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{2}
}

// ProvisionAccountRequest carries ids that are the caller's, because the claim
// settled them.
type ProvisionAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	PersonId      string                 `protobuf:"bytes,2,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	Eid           string                 `protobuf:"bytes,3,opt,name=eid,proto3" json:"eid,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	EmailId       string                 `protobuf:"bytes,5,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionAccountRequest) Reset() {
	*x = ProvisionAccountRequest{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionAccountRequest) ProtoMessage() {}

func (x *ProvisionAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionAccountRequest.ProtoReflect.Descriptor instead.
func (*ProvisionAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionAccountRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ProvisionAccountRequest) GetPersonId() string {
	if x != nil {
		return x.PersonId
	}
	return ""
}

func (x *ProvisionAccountRequest) GetEid() string {
	if x != nil {
		return x.Eid
	}
	return ""
}

func (x *ProvisionAccountRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ProvisionAccountRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *ProvisionAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProvisionAccountRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ProvisionAccountRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type ProvisionAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionAccountResponse) Reset() {
	*x = ProvisionAccountResponse{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionAccountResponse) ProtoMessage() {}

func (x *ProvisionAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionAccountResponse.ProtoReflect.Descriptor instead.
func (*ProvisionAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ProvisionAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type ListTenantUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Skip          int32                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	SearchText    string                 `protobuf:"bytes,6,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantUsersRequest) Reset() {
	*x = ListTenantUsersRequest{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantUsersRequest) ProtoMessage() {}

func (x *ListTenantUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantUsersRequest.ProtoReflect.Descriptor instead.
func (*ListTenantUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ListTenantUsersRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ListTenantUsersRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListTenantUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTenantUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListTenantUsersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTenantUsersRequest) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

// ListTenantUsersResponse is a page plus the unpaginated total.
type ListTenantUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Data          []*Account             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantUsersResponse) Reset() {
	*x = ListTenantUsersResponse{}
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantUsersResponse) ProtoMessage() {}

func (x *ListTenantUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantUsersResponse.ProtoReflect.Descriptor instead.
func (*ListTenantUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ListTenantUsersResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListTenantUsersResponse) GetData() []*Account {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_primeage_auth_auth_proto protoreflect.FileDescriptor

const file_proto_primeage_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/primeage/auth/auth.proto\x12\rprimeage.auth\"\xff\x01\n" +
	"\aAccount\x12\x1b\n" +
	"\tunique_id\x18\x01 \x01(\tR\buniqueId\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\bemail_id\x18\x03 \x01(\tR\aemailId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x16\n" +
	"\x06domain\x18\x06 \x01(\tR\x06domain\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\"\n" +
	"\rlast_login_at\x18\t \x01(\tR\vlastLoginAt\"5\n" +
	"\x1bPrepareTenantStorageRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\x1e\n" +
	"\x1cPrepareTenantStorageResponse\"\xe5\x01\n" +
	"\x17ProvisionAccountRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1b\n" +
	"\tperson_id\x18\x02 \x01(\tR\bpersonId\x12\x10\n" +
	"\x03eid\x18\x03 \x01(\tR\x03eid\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\bemail_id\x18\x05 \x01(\tR\aemailId\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\"L\n" +
	"\x18ProvisionAccountResponse\x120\n" +
	"\aaccount\x18\x01 \x01(\v2\x16.primeage.auth.AccountR\aaccount\"\xa7\x01\n" +
	"\x16ListTenantUsersRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x05R\x04skip\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vsearch_text\x18\x06 \x01(\tR\n" +
	"searchText\"[\n" +
	"\x17ListTenantUsersResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.primeage.auth.AccountR\x04data2\xcb\x02\n" +
	"\vAuthService\x12q\n" +
	"\x14PrepareTenantStorage\x12*.primeage.auth.PrepareTenantStorageRequest\x1a+.primeage.auth.PrepareTenantStorageResponse\"\x00\x12e\n" +
	"\x10ProvisionAccount\x12&.primeage.auth.ProvisionAccountRequest\x1a'.primeage.auth.ProvisionAccountResponse\"\x00\x12b\n" +
	"\x0fListTenantUsers\x12%.primeage.auth.ListTenantUsersRequest\x1a&.primeage.auth.ListTenantUsersResponse\"\x00B8Z6github.com/primeage-health/primeageutils/genproto/authb\x06proto3"

var (
	file_proto_primeage_auth_auth_proto_rawDescOnce sync.Once
	file_proto_primeage_auth_auth_proto_rawDescData []byte
)

func file_proto_primeage_auth_auth_proto_rawDescGZIP() []byte {
	file_proto_primeage_auth_auth_proto_rawDescOnce.Do(func() {
		file_proto_primeage_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_primeage_auth_auth_proto_rawDesc), len(file_proto_primeage_auth_auth_proto_rawDesc)))
	})
	return file_proto_primeage_auth_auth_proto_rawDescData
}

var file_proto_primeage_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_primeage_auth_auth_proto_goTypes = []any{
	(*Account)(nil),                      // 0: primeage.auth.Account
	(*PrepareTenantStorageRequest)(nil),  // 1: primeage.auth.PrepareTenantStorageRequest
	(*PrepareTenantStorageResponse)(nil), // 2: primeage.auth.PrepareTenantStorageResponse
	(*ProvisionAccountRequest)(nil),      // 3: primeage.auth.ProvisionAccountRequest
	(*ProvisionAccountResponse)(nil),     // 4: primeage.auth.ProvisionAccountResponse
	(*ListTenantUsersRequest)(nil),       // 5: primeage.auth.ListTenantUsersRequest
	(*ListTenantUsersResponse)(nil),      // 6: primeage.auth.ListTenantUsersResponse
}
var file_proto_primeage_auth_auth_proto_depIdxs = []int32{
	0, // 0: primeage.auth.ProvisionAccountResponse.account:type_name -> primeage.auth.Account
	0, // 1: primeage.auth.ListTenantUsersResponse.data:type_name -> primeage.auth.Account
	1, // 2: primeage.auth.AuthService.PrepareTenantStorage:input_type -> primeage.auth.PrepareTenantStorageRequest
	3, // 3: primeage.auth.AuthService.ProvisionAccount:input_type -> primeage.auth.ProvisionAccountRequest
	5, // 4: primeage.auth.AuthService.ListTenantUsers:input_type -> primeage.auth.ListTenantUsersRequest
	2, // 5: primeage.auth.AuthService.PrepareTenantStorage:output_type -> primeage.auth.PrepareTenantStorageResponse
	4, // 6: primeage.auth.AuthService.ProvisionAccount:output_type -> primeage.auth.ProvisionAccountResponse
	6, // 7: primeage.auth.AuthService.ListTenantUsers:output_type -> primeage.auth.ListTenantUsersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_primeage_auth_auth_proto_init() }
func file_proto_primeage_auth_auth_proto_init() {
	if File_proto_primeage_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_primeage_auth_auth_proto_rawDesc), len(file_proto_primeage_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_primeage_auth_auth_proto_goTypes,
		DependencyIndexes: file_proto_primeage_auth_auth_proto_depIdxs,
		MessageInfos:      file_proto_primeage_auth_auth_proto_msgTypes,
	}.Build()
	File_proto_primeage_auth_auth_proto = out.File
	file_proto_primeage_auth_auth_proto_goTypes = nil
	file_proto_primeage_auth_auth_proto_depIdxs = nil
}
