// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/primeage/auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_PrepareTenantStorage_FullMethodName  = "/primeage.auth.AuthService/PrepareTenantStorage"
	AuthService_ProvisionAccount_FullMethodName      = "/primeage.auth.AuthService/ProvisionAccount"
	AuthService_ListTenantUsers_FullMethodName       = "/primeage.auth.AuthService/ListTenantUsers"
	AuthService_IssuePortalCredential_FullMethodName = "/primeage.auth.AuthService/IssuePortalCredential"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthService is what backend.primeage.life may ask of auth.primeage.life.
//
// The split leaves each service holding half of what provisioning needs: backend
// owns the person an account belongs to and the registry row of the tenant it
// lives in, auth owns the tenant's accounts and their indexes. This is the whole
// of that surface — three methods, all of them things only auth can do.
//
// Callers are services, so nothing here takes a caller domain or a session
// actor. The service token in metadata is the authentication; the actor arrives
// in the request as the admin who initiated the onboarding.
type AuthServiceClient interface {
	// PrepareTenantStorage declares a tenant's auth collection and its indexes.
	// Idempotent, so a retried onboarding calls it again harmlessly.
	PrepareTenantStorage(ctx context.Context, in *PrepareTenantStorageRequest, opts ...grpc.CallOption) (*PrepareTenantStorageResponse, error)
	// ProvisionAccount writes an account whose person the caller already claimed,
	// adopting the person and account ids the caller settled on rather than
	// minting its own. Idempotent on the phone number within the tenant, so a
	// retried onboarding returns the existing account rather than failing.
	ProvisionAccount(ctx context.Context, in *ProvisionAccountRequest, opts ...grpc.CallOption) (*ProvisionAccountResponse, error)
	// ListTenantUsers returns a page of one tenant's accounts, for the admin
	// console's drill-in to an agency.
	ListTenantUsers(ctx context.Context, in *ListTenantUsersRequest, opts ...grpc.CallOption) (*ListTenantUsersResponse, error)
	// IssuePortalCredential sets a password for a person who holds no membership
	// yet — an agency applicant, who needs a way into the onboarding portal before
	// any tenant of theirs exists.
	//
	// It is the one method here that returns a credential rather than taking one.
	// The caller mails it and keeps it nowhere; auth stores only the hash, so a
	// lost password is reissued rather than recovered. Calling it again replaces
	// the password, which is what makes a retried registration safe.
	IssuePortalCredential(ctx context.Context, in *IssuePortalCredentialRequest, opts ...grpc.CallOption) (*IssuePortalCredentialResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) PrepareTenantStorage(ctx context.Context, in *PrepareTenantStorageRequest, opts ...grpc.CallOption) (*PrepareTenantStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareTenantStorageResponse)
	err := c.cc.Invoke(ctx, AuthService_PrepareTenantStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ProvisionAccount(ctx context.Context, in *ProvisionAccountRequest, opts ...grpc.CallOption) (*ProvisionAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionAccountResponse)
	err := c.cc.Invoke(ctx, AuthService_ProvisionAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListTenantUsers(ctx context.Context, in *ListTenantUsersRequest, opts ...grpc.CallOption) (*ListTenantUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantUsersResponse)
	err := c.cc.Invoke(ctx, AuthService_ListTenantUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) IssuePortalCredential(ctx context.Context, in *IssuePortalCredentialRequest, opts ...grpc.CallOption) (*IssuePortalCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuePortalCredentialResponse)
	err := c.cc.Invoke(ctx, AuthService_IssuePortalCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
//
// AuthService is what backend.primeage.life may ask of auth.primeage.life.
//
// The split leaves each service holding half of what provisioning needs: backend
// owns the person an account belongs to and the registry row of the tenant it
// lives in, auth owns the tenant's accounts and their indexes. This is the whole
// of that surface — three methods, all of them things only auth can do.
//
// Callers are services, so nothing here takes a caller domain or a session
// actor. The service token in metadata is the authentication; the actor arrives
// in the request as the admin who initiated the onboarding.
type AuthServiceServer interface {
	// PrepareTenantStorage declares a tenant's auth collection and its indexes.
	// Idempotent, so a retried onboarding calls it again harmlessly.
	PrepareTenantStorage(context.Context, *PrepareTenantStorageRequest) (*PrepareTenantStorageResponse, error)
	// ProvisionAccount writes an account whose person the caller already claimed,
	// adopting the person and account ids the caller settled on rather than
	// minting its own. Idempotent on the phone number within the tenant, so a
	// retried onboarding returns the existing account rather than failing.
	ProvisionAccount(context.Context, *ProvisionAccountRequest) (*ProvisionAccountResponse, error)
	// ListTenantUsers returns a page of one tenant's accounts, for the admin
	// console's drill-in to an agency.
	ListTenantUsers(context.Context, *ListTenantUsersRequest) (*ListTenantUsersResponse, error)
	// IssuePortalCredential sets a password for a person who holds no membership
	// yet — an agency applicant, who needs a way into the onboarding portal before
	// any tenant of theirs exists.
	//
	// It is the one method here that returns a credential rather than taking one.
	// The caller mails it and keeps it nowhere; auth stores only the hash, so a
	// lost password is reissued rather than recovered. Calling it again replaces
	// the password, which is what makes a retried registration safe.
	IssuePortalCredential(context.Context, *IssuePortalCredentialRequest) (*IssuePortalCredentialResponse, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) PrepareTenantStorage(context.Context, *PrepareTenantStorageRequest) (*PrepareTenantStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareTenantStorage not implemented")
}
func (UnimplementedAuthServiceServer) ProvisionAccount(context.Context, *ProvisionAccountRequest) (*ProvisionAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionAccount not implemented")
}
func (UnimplementedAuthServiceServer) ListTenantUsers(context.Context, *ListTenantUsersRequest) (*ListTenantUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenantUsers not implemented")
}
func (UnimplementedAuthServiceServer) IssuePortalCredential(context.Context, *IssuePortalCredentialRequest) (*IssuePortalCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssuePortalCredential not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_PrepareTenantStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTenantStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PrepareTenantStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PrepareTenantStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PrepareTenantStorage(ctx, req.(*PrepareTenantStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ProvisionAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ProvisionAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ProvisionAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ProvisionAccount(ctx, req.(*ProvisionAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListTenantUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListTenantUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListTenantUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListTenantUsers(ctx, req.(*ListTenantUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_IssuePortalCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePortalCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IssuePortalCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_IssuePortalCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IssuePortalCredential(ctx, req.(*IssuePortalCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "primeage.auth.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareTenantStorage",
			Handler:    _AuthService_PrepareTenantStorage_Handler,
		},
		{
			MethodName: "ProvisionAccount",
			Handler:    _AuthService_ProvisionAccount_Handler,
		},
		{
			MethodName: "ListTenantUsers",
			Handler:    _AuthService_ListTenantUsers_Handler,
		},
		{
			MethodName: "IssuePortalCredential",
			Handler:    _AuthService_IssuePortalCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/primeage/auth/auth.proto",
}
