// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/primeage/mailer/mailer.proto

package mailer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListTemplatesRequest takes no arguments.
//
// It exists rather than google.protobuf.Empty so that a filter — by domain, or
// by whether a template is safe for an operator to choose — can be added later
// without a new method and a new client call site.
type ListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesRequest) Reset() {
	*x = ListTemplatesRequest{}
	mi := &file_proto_primeage_mailer_mailer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesRequest) ProtoMessage() {}

func (x *ListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_mailer_mailer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_primeage_mailer_mailer_proto_rawDescGZIP(), []int{0}
}

// ListTemplatesResponse is every template a send may name, name-ordered.
//
// The order is part of the contract: the registry behind it is a map, and an
// unordered list would differ between two calls, so a caller diffing it would
// see a change that is not one.
type ListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*MailTemplate        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTemplatesResponse) Reset() {
	*x = ListTemplatesResponse{}
	mi := &file_proto_primeage_mailer_mailer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTemplatesResponse) ProtoMessage() {}

func (x *ListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_mailer_mailer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_primeage_mailer_mailer_proto_rawDescGZIP(), []int{1}
}

func (x *ListTemplatesResponse) GetTemplates() []*MailTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// MailTemplate is one message this service knows how to send.
type MailTemplate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// required_keys are the data keys a send must supply. A missing one is
	// refused rather than rendered blank.
	RequiredKeys []string `protobuf:"bytes,3,rep,name=required_keys,json=requiredKeys,proto3" json:"required_keys,omitempty"`
	// secret_keys are the required keys whose values carry a credential — a
	// one-time code, a portal password. This service redacts them before writing
	// its delivery log; naming them is what lets a caller keep them out of its
	// own.
	SecretKeys    []string `protobuf:"bytes,4,rep,name=secret_keys,json=secretKeys,proto3" json:"secret_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MailTemplate) Reset() {
	*x = MailTemplate{}
	mi := &file_proto_primeage_mailer_mailer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MailTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailTemplate) ProtoMessage() {}

func (x *MailTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_primeage_mailer_mailer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailTemplate.ProtoReflect.Descriptor instead.
func (*MailTemplate) Descriptor() ([]byte, []int) {
	return file_proto_primeage_mailer_mailer_proto_rawDescGZIP(), []int{2}
}

func (x *MailTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MailTemplate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *MailTemplate) GetRequiredKeys() []string {
	if x != nil {
		return x.RequiredKeys
	}
	return nil
}

func (x *MailTemplate) GetSecretKeys() []string {
	if x != nil {
		return x.SecretKeys
	}
	return nil
}

var File_proto_primeage_mailer_mailer_proto protoreflect.FileDescriptor

const file_proto_primeage_mailer_mailer_proto_rawDesc = "" +
	"\n" +
	"\"proto/primeage/mailer/mailer.proto\x12\x0fprimeage.mailer\"\x16\n" +
	"\x14ListTemplatesRequest\"T\n" +
	"\x15ListTemplatesResponse\x12;\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1d.primeage.mailer.MailTemplateR\ttemplates\"\x82\x01\n" +
	"\fMailTemplate\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12#\n" +
	"\rrequired_keys\x18\x03 \x03(\tR\frequiredKeys\x12\x1f\n" +
	"\vsecret_keys\x18\x04 \x03(\tR\n" +
	"secretKeys2q\n" +
	"\rMailerService\x12`\n" +
	"\rListTemplates\x12%.primeage.mailer.ListTemplatesRequest\x1a&.primeage.mailer.ListTemplatesResponse\"\x00B:Z8github.com/primeage-health/primeageutils/genproto/mailerb\x06proto3"

var (
	file_proto_primeage_mailer_mailer_proto_rawDescOnce sync.Once
	file_proto_primeage_mailer_mailer_proto_rawDescData []byte
)

func file_proto_primeage_mailer_mailer_proto_rawDescGZIP() []byte {
	file_proto_primeage_mailer_mailer_proto_rawDescOnce.Do(func() {
		file_proto_primeage_mailer_mailer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_primeage_mailer_mailer_proto_rawDesc), len(file_proto_primeage_mailer_mailer_proto_rawDesc)))
	})
	return file_proto_primeage_mailer_mailer_proto_rawDescData
}

var file_proto_primeage_mailer_mailer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_primeage_mailer_mailer_proto_goTypes = []any{
	(*ListTemplatesRequest)(nil),  // 0: primeage.mailer.ListTemplatesRequest
	(*ListTemplatesResponse)(nil), // 1: primeage.mailer.ListTemplatesResponse
	(*MailTemplate)(nil),          // 2: primeage.mailer.MailTemplate
}
var file_proto_primeage_mailer_mailer_proto_depIdxs = []int32{
	2, // 0: primeage.mailer.ListTemplatesResponse.templates:type_name -> primeage.mailer.MailTemplate
	0, // 1: primeage.mailer.MailerService.ListTemplates:input_type -> primeage.mailer.ListTemplatesRequest
	1, // 2: primeage.mailer.MailerService.ListTemplates:output_type -> primeage.mailer.ListTemplatesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_primeage_mailer_mailer_proto_init() }
func file_proto_primeage_mailer_mailer_proto_init() {
	if File_proto_primeage_mailer_mailer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_primeage_mailer_mailer_proto_rawDesc), len(file_proto_primeage_mailer_mailer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_primeage_mailer_mailer_proto_goTypes,
		DependencyIndexes: file_proto_primeage_mailer_mailer_proto_depIdxs,
		MessageInfos:      file_proto_primeage_mailer_mailer_proto_msgTypes,
	}.Build()
	File_proto_primeage_mailer_mailer_proto = out.File
	file_proto_primeage_mailer_mailer_proto_goTypes = nil
	file_proto_primeage_mailer_mailer_proto_depIdxs = nil
}
